# Generated by Django 5.2.6 on 2025-10-02 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_reports', 'Can view reports'), ('can_edit_menu', 'Can edit menu')]},
        ),
    ]
